#!/bin/bash

# Test PDF Generation Server
# This script tests if the PDF server correctly returns binary PDF data

echo "🧪 Testing PDF Generation Server..."
echo ""

# Check if server is running
if ! curl -s http://localhost:3000/health > /dev/null 2>&1; then
    echo "❌ Server is not running on port 3000"
    echo "Please start the server with: npm start"
    exit 1
fi

echo "✅ Server is running"
echo ""

# Test PDF generation
echo "📄 Generating test PDF..."
curl -X POST http://localhost:3000/generate \
  -H "Content-Type: application/json" \
  -H "X-API-Key: ${API_KEY:-test-key}" \
  -d '{"html":"<html><head><style>body{font-family:Arial;padding:20px;}h1{color:#333;}</style></head><body><h1>Test PDF Document</h1><p>This is a test PDF generated by the pdf-forge server.</p><p>If you can read this, the PDF generation is working correctly!</p></body></html>"}' \
  --output test-output.pdf \
  --silent \
  --show-error

# Check if file was created
if [ ! -f test-output.pdf ]; then
    echo "❌ Failed to create PDF file"
    exit 1
fi

# Check file size
FILE_SIZE=$(stat -f%z test-output.pdf 2>/dev/null || stat -c%s test-output.pdf 2>/dev/null)
if [ "$FILE_SIZE" -lt 100 ]; then
    echo "❌ PDF file is too small ($FILE_SIZE bytes)"
    echo "File contents:"
    cat test-output.pdf
    exit 1
fi

# Check if it's a valid PDF
if file test-output.pdf | grep -q "PDF"; then
    echo "✅ Valid PDF file created ($FILE_SIZE bytes)"
    echo ""
    echo "📊 File details:"
    file test-output.pdf
    echo ""
    echo "🎉 Success! PDF generation is working correctly."
    echo "📁 Test file saved as: test-output.pdf"
else
    echo "❌ File is not a valid PDF"
    echo "File type:"
    file test-output.pdf
    echo ""
    echo "First 100 bytes:"
    head -c 100 test-output.pdf
    exit 1
fi
